### ISSUE TITLE
time picker

### ISSUE THREAD

**Issue by Sohalt** [basic-web-components/basic-web-components#10]
I'd like to suggest to add a time picker in the style of the android time pickers, that is,  essentially a depiction of an analog clock where the mouse controls the position of the hands and therefore the time chosen. This interface provides the same benefits as pie menus, in that it allows for increased accuracy and control by simply moving the mouse pointer further from the center of the widget, therefore increasing the target area. (http://9to5google.com/2013/05/30/google-calendar-for-android-updated-with-custom-colors-redesigned-datetime-pickers/)

**Comment by JanMiksovsky** [comment]
@Sohalt Thanks for the suggestion. I've folded this into our list of desired components.

This will likely require a good deal of thought. We'd like to provide a comprehensive solution for date and time components for both desktop and mobile. Designers and developers will likely want those to be responsive, or at least have some responsive variants that decide whether to show a desktop-optimized or mobile-optimized UI. The latter gets more complex because of the presence of OS-specific UI patterns the user may be expecting. So there's a lot to work through here.

That said, this is a good idea to capture.
