### ISSUE TITLE
pie menu

### ISSUE THREAD

**Issue by Sohalt** [basic-web-components/basic-web-components#11]
I'd like to propose to add a pie menu component.

Some reference on what and why:
http://www.donhopkins.com/drupal/node/98
https://en.wikipedia.org/wiki/Pie_menu

**Comment by JanMiksovsky** [comment]
Pie menus are an interesting user interface idea, but I'm not sure they meet our criterion of being a very common user interface patterns. There are certainly many apps that have tried them, and there may be situations where they're an excellent idea. But they are nevertheless relatively rare in modern applications

I think you've touched an important philosophical point for this project that we should clarify in our docs. I've added the following to our top-level README:

> We welcome new ideas. Please keep in mind that our goal is to provide great
implementations of the patterns people are already doing — the basic elements of
user interface design — not to design or promote user interface innovations. If
someone invents a great new user interface solution, we probably won't include
an implementation of that idea right away until a large number of
sites/applications have adopted it (or are interested in adopting it).

I don't think pie menus satisfy our criteria yet. Although they've been around for a long time, they still feel experimental. This is obviously an subjective judgment, and any decision now could be revisited if interest in a design pattern changes. If it's okay with you, though, I'd like to close this for now.

**Comment by Sohalt** [comment]
It's sad to hear that but completely understandable given the points you've stated. To me it feels like a large part of why pie menus are underrepresented is that to few people know them and additionally there don't exist well implemented and easy to use libraries for using pie menus, i.e. graphical toolkits include buttons and drop downs, but no pie menus. It might be a little bit of a chicken egg problem, which is why I think it is important to also provide really good implementations of less common but conceptually sound and in some cases advantageous UI elements. But maybe that calls for another project, which could explicitly try to promote adoption of more exotic stuff and provide room for experimentation (although I think pie menus are beyond the experimental state and well proven).

Am 3. Februar 2016 01:27:16 MEZ, schrieb Jan Miksovsky <notifications@github.com>:

**Comment by JanMiksovsky** [comment]
@Sohalt, I completely understand how you feel. I've found or created many user interface designs that, while interesting, are not *yet* common enough to add to this library. For example, I would love to add the [time picker](http://miksovsky.blogs.com/flowstate/2010/10/reconsidering-stock-controls-to-create-an-optimized-user-experience.html) I designed for Cozi.com. It solves a number of user interface problems, and does very well in usability tests. But's unique, and likely to stay that way for the foreseeable future.

That said, I don't want to lose suggestions. Design patterns go in and out of style, and it's worth us keeping a list of ideas like this that we want to keep an eye on. With that in mind, I'm moving the "Desired Components" section of the top-level README to a new wiki page for [Desired Components](https://github.com/basic-web-components/basic-web-components/wiki/Desired-Components).

I've broken that into two sections: "Very common user interface patterns" and "Other established user interface patterns". Since pie menus are a well-established, but not particularly common, I've included your suggestion in the second section.

I also like your idea of having a separate project for web components that are very promising but not yet mainstream.

Thanks for putting pie menus on our list, and feel free to add more things to that page (in either section).
