### ISSUE TITLE
basic-shared in iron-pages: performance collapse

### ISSUE THREAD

**Issue by Jamtis** [basic-web-components/basic-web-components#16]
I recognized a drastical performance collapse when a `basic-carousel` is embedded in a page of `iron-pages`.
```
<dom-module id="test-element">
    <template>
        <paper-tabs selected="{{selected}}">
            <paper-tab>First</paper-tab>
            <paper-tab>Second</paper-tab>
        </paper-tabs>
        <iron-pages selected="{{selected}}">
            <basic-arrow-direction selected-index="0" target="child"
                                   class="overlay" aria-label="Images" role="listbox">
                <basic-page-dots target="child">
                    <basic-carousel>
                        <content select="div"></content>
                    </basic-carousel>
                </basic-page-dots>
            </basic-arrow-direction>
            <div>Second</div>
        </iron-pages>
    </template>
</dom-module>
```
[Here's a demo](https://jamtis.github.io/basic-web-components/demo/demo.html)
When switching between the iron-pages the performance goes progressively down. (Note: switching the pages of `basic-carousel` is irrelevant).

I found out that the issue is related to functions in `basic-shared.js`.

[`lightDomContentChanged`](https://github.com/Jamtis/basic-web-components/blob/gh-pages/src/basic-shared/ContentChanged.js#L197) gets exponentially often called when switching the `iron-pages`, as you can see from the [timeline](https://github.com/Jamtis/basic-web-components/blob/gh-pages/demo/TimelineRawData-iron-pages-performance-issue.json).

The issue only occurs when `basic-carousel` has `<content>`.

@JanMiksovsky This issue digs a bit deeper into the code than the ones I reported before.
I hope my superficial analysis helps you with your debugging.
Actually I would like to resolve the issue myself but I currently don't have the time to dig into the core code.
Please tell me what your thoughts are on this one, especially if this bug can be resolved in the near future... (I know it's hard to tell but you are more into the core than anyone).

If the fix takes some time I'll go with a shady workaround:

Erasing [lightDomContentChanged](https://github.com/Jamtis/basic-web-components/blob/gh-pages/src/basic-shared/ContentChanged.js#L197) works for me but it's an extremely dirty solution.
Maybe it helps you debugging.

I would really prefer a clean solution to this problem because this behavior points to a more fundamental and unpredictable problem.
My personal guess: Somewhere in `basic-shared.js` Listeners/MutationObservers are set where they shouldn't be set.

Thanks in advance.

**Comment by Jamtis** [comment]
I may have a clue what causes this behavior...
Could be [this TODO:](https://github.com/basic-web-components/basic-web-components/blob/master/src/basic-shared/ContentChanged.js#L191) which doesn't remove old observers and therefore create too many listeners.

**Comment by Jamtis** [comment]
Adding `stopObservingContentMutations(node);` before [this line](https://github.com/basic-web-components/basic-web-components/blob/master/src/basic-shared/ContentChanged.js#L164).solves the problem for me.
I'm not absolutely sure if it's the right place for stopping observing as I don't know all implications.

**Comment by JanMiksovsky** [comment]
Sorry that you're hitting this issue. We can confirm that we've also seen performance issues in certain cases and, as you've deduced, the problem lies in the way we use mutation observers.

We're currently rewriting the code that tracks content changes. We will use your code above as a repro case and will try to resolve this performance issue in our rewrite. We hope to complete that rewrite in the 0.7 release, currently planned for the next 3–4 weeks.

**Comment by Jamtis** [comment]
Updated to 0.7 - performance goes still down on 0.6.4.
0.7 gives me a JS error...
`Cannot read property 'assimilate' of undefined` in `TargetInCollective.js:22`.
Maybe you'll have a look at it.

**Comment by JanMiksovsky** [comment]
Sorry we haven't had a chance to look at this during the 0.7 work. An investigation into the new error and (once that error is fixed) the underlying performance issue is on our backlog. Thanks for your patience.

**Comment by Jamtis** [comment]
:+1:

**Comment by Jamtis** [comment]
Current state?

**Comment by JanMiksovsky** [comment]
Sorry for the delay. I'm looking into this now.

**Comment by JanMiksovsky** [comment]
I've posted a working of version of this at https://gist.github.com/JanMiksovsky/2415995251b0d9941c44c4a9a2cf75c0. The styling doesn't look pretty, but the component appears to generally function.

There are multiple levels to the problem here.
* The basic-arrow-selection and basic-page-dots elements no longer need a `target="child"` attribute. In fact, setting that attribute triggers the "assimilate" error. Removing that attribute fixes that part of the issue.
* A bug in the ItemsSelect mixin prevented the example from working. I've fixed that in [254de774](https://gist.github.com/JanMiksovsky/2415995251b0d9941c44c4a9a2cf75c0). That fix will go out in the next release, 0.7.6, probably sometime in the next few weeks. Thanks for helping find this bug.

The original performance issue here was a result of using MutationObservers in a suboptimal way. The good news is that the components no longer have that problem. The bad news is the component no longer properly detect dynamic content changes. An element like basic-carousel can tell when its children have changed, but when basic-carousel is used inside another component like test-element here, basic-carousel cannot properly detect when test-element's children change. So if you dynamically use `appendChild()` to add a new child to test-element, you won't see basic-page-dots update the number of dots shown. The W3C is currently working out the details for a Shadow DOM event called `slotChanged` that will let components like basic-carousel work in cases like this.

One remaining oddity I noticed is that that the carousel in this example doesn't seem to be responding to the keyboard as I expect. Normally, clicking on a carousel should give it the keyboard focus, but that doesn't work in this example. It's possible that paper-tabs or iron-pages is doing something to manipulate focus. Let me know if you have concerns about that and I can try to investigate that separately.

**Comment by Jamtis** [comment]
slotChanged will do the job.:+1:
The question about the focus: This is a general problem due to the two-level navigation.
I think we should stick to the current behavior until someone raises a serious concern about this.

The original issue is deprecated, so this can be close I guess.

**Comment by JanMiksovsky** [comment]
Okay, thanks for following up.
