### ISSUE TITLE
Consider standard conform button usage

### ISSUE THREAD

**Issue by Jamtis** [basic-web-components/basic-web-components#20]
Officially `<button>` elements should only have "phrasing content" as stated in the [MDN](https://developer.mozilla.org/de/docs/Web/HTML/Element/button) and in the W3C draft.

I think it's a longterm goal to use all native elements in a standardized way.

I came across this problem when I tried to compile `<basic-arrow-direction>` with kangax' htmlmin@1.3.0 (see kangax/html-minifier#565) which broke the code.

What's your opinion about replacing invalid buttons in the future?

**Comment by JanMiksovsky** [comment]
I don't believe it's the case that buttons can only contain phrasing content. At least one [spec for the button element](http://w3c.github.io/html/sec-forms.html#elementdef-button) indicates that buttons can support for a broader variety of content types, including flow content.

In any event, it's clear that buttons should be able to contain custom elements. Generally speaking, I would think that a tool that processes HTML should permit the inclusion of custom elements anywhere.

To help answer the question about how tools like html-minifier should handle custom elements, I've raised this as a [question on w3c/webcomponents](https://github.com/w3c/webcomponents/issues/454).

**Comment by Jamtis** [comment]
Appreciate the effort.

**Comment by JanMiksovsky** [comment]
The latest spec [indicates](https://w3c.github.io/webcomponents/spec/custom/#custom-elements-core-concepts) that custom elements can be used "where phrasing content is expected".

So I think HTML tools like htmlmin should be extended to support the use of custom elements inside of elements like `<button>`. You could file an issue on htmlmin and point at the new spec.

Many thanks for raising the original issue so that this could get officially resolved in a W3C spec. I don't think there's anything more for me to do here, so I'm going to close this issue.
