### ISSUE TITLE
Making 0.8.0 work with customElements.define and new release date?

### ISSUE THREAD

**Issue by svastanesto** [basic-web-components/basic-web-components#30]
Hi, 

I wonder when will the latest version of the code (the master branch) be available through npm? 

I am using `window.customElements.define("my-component", MyComponent)` to register my components. And when I try to extend WrappedStandardElement from 0.8.0 version like `class MyComponent extends WrappedStandardElement.wrap("a")`  I get an error "Class constructor Wrapped cannot be invoked without 'new'".  

If I import WrappedStandardElement from your master branch version (where you also switched to using define instead of registerElement) it works without problem. 

So, any plans for making it available soon or is there a way to make customElements.define work with 0.8.0? 

Thank you!

**Comment by JanMiksovsky** [comment]
@svastanesto Thank you for your question. As it turns out, for the last half year we've been busy expanding the ideas and components in Basic Web Components into a new, larger project called [Elix](https://github.com/elix/elix). We've been so focused on that, we hadn't gotten around to updating the status of Basic Web Components. I've just updated this project's ReadMe to reflect the fact that Basic Web Components is no longer under active development. My apologies for not updating the project's status earlier, and for any difficulties this change causes you.

It's our intention to migrate WrappedStandardElement to Elix so that we can use it for the basis of components like AutosizeTextarea. We hadn't been aware of people using WrappedStandardElement directly, so it hadn't been high on the priority list for Elix. But if that component is important to you, we can increase its priority. I'd be interested in hearing more about how you're using that component.

Elix uses Shadow DOM v1 and Custom Elements v1, so all its components are registered via `customElements.define`. We're preparing to make an initial project release via npm, but for the time being the only way to pick up Elix components is via dependencies on the GitHub repository at `elix/elix`.

**Comment by svastanesto** [comment]
Hi Jan,

Thank you for the update. The Elix project looks very interesting, I will take a closer look. 
It is weird that I did not stumble upon when looking for examples of web components without Polymer. Those examples are difficult to find, so I really appreciate your team's awesome work! (Maybe add "vanilla js web components" as keywords in project description or tags?)

We are in early stages of trying to use web components in our project, so we are just trying different approaches still. 

Since there is a disagreement about extending native html elements as in v1 specification, the only way to go is to wrap the basic elements that we want to extend (like links, buttons etc). I find wrapped component with the MarshallingMixin is very useful, since then it does feel like extending the native element, although i feel a bit unsure about the fact that it is hiding what it does, for example by inspecting our MyLink component that extends the wrapped element you cannot know that the attribute changes will be mapped to property updates, nor which attributes are supported. If we we have that automatic marshaling for one component, then one will probably expect that the rest of our components should have the same behavior, regardless of if they are intended as extend of native elements.  

But we might skip the wrapped component, and just use the marshaling mixin, since we need to modify the template anyway. At this stage we are trying to find a setup that works for our needs. But it would be interesting to see how will you use it. Would you use it for buttons and regular links as well? I wonder if it is a overkill for simpler elements... 

Btw, no plans to support IE 11 in Elix? :/

**Comment by JanMiksovsky** [comment]
Thanks for taking a look at Elix. I'd like to respond to your questions, but since they go beyond the scope of this original issue and project, perhaps we can move the conversation to email and we can close this particular issue. Please contact me at jan@component.kitchen, and I'll do my best to answer your questions in mail. Alternatively, we can start a discussion on the elix/elix repo.
