### ISSUE TITLE
polymer 1.0 TypeError on initialization

### ISSUE THREAD

**Issue by canufeel** [basic-web-components/basic-web-components#6]
Error on element initialization.

Uncaught TypeError: Basic.Collective is not a function

in basic-aspect line 39.

window.Basic.Aspect.created @ vulcanized.html:6488Polymer.Base._addFeature._invokeBehavior @ vulcanized.html:273(anonymous function) @ vulcanized.html:266Polymer.Base._addFeature._doBehavior @ vulcanized.html:265Polymer.Base.createdCallback @ vulcanized.html:97prototype.createElement @ ember.debug.js:2602build @ index.js:63render @ index.js:82renderHTMLBarsTemplate @ ember.debug.js:8491renderView @ ember.debug.js:8463renderView @ ember.debug.js:35400mixin.Mixin.create.render @ ember.debug.js:35423EmberRenderer_createElement @ ember.debug.js:37468Renderer_renderTree @ ember.debug.js:9140scheduledRenderTree @ ember.debug.js:9216Queue.invoke @ ember.debug.js:878Queue.flush @ ember.debug.js:943DeferredActionQueues.flush @ ember.debug.js:748Backburner.end @ ember.debug.js:173Backburner.run @ ember.debug.js:228Backburner.join @ ember.debug.js:247run.join @ ember.debug.js:15904run.bind @ ember.debug.js:15966jQuery.Callbacks.fire @ jquery.js:3148jQuery.Callbacks.self.fireWith @ jquery.js:3260jQuery.extend.ready @ jquery.js:3472completed @ jquery.js:3503

Here is my bower.json deps:

"dependencies": {
    "ember": "1.12.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.0.0-beta.18",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
    "ember-qunit": "0.3.3",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.15",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1",
    "hammerjs": "1.1.3",
    "ember-hammer": "~1.0.0",
    "polymer": "Polymer/polymer#^1.0.0",
    "iron-elements": "PolymerElements/iron-elements#~1.0.1",
    "basic-carousel": "basic-web-components/basic-carousel#master",
    "basic-arrow-direction": "basic-web-components/basic-arrow-direction#master",
    "basic-page-dots": "basic-web-components/basic-page-dots#master"
  }

**Comment by JanMiksovsky** [comment]
@canufeel Thanks for the report. I'll investigate.

**Comment by JanMiksovsky** [comment]
I just did a quick check to make sure that basic-aspect on the master branch can be instantiated, and it can. I'm not seeing this exception.

There are two classes implicated in this issue: Basic.Aspect and Basic.Collective. The first depends on the second, but it sounds like second (Basic.Collective) isn't defined by the time Basic.Aspect needs it.

Since it looks like you're using vulcanize, and vulcanize can potentially have unintended effects on the order in which scripts, etc., are evaluated, can you check the following?

1. Look in your vulcanized file (vulcanized.html) for the line mentioned in the bug:
```
    new Basic.Collective(this);
```

2. Now look in the same vulcanized file for the line that defined Basic.Collective:
```
function Collective() {
```

Please let me know if the line for #1 comes *after* the line for #2.

**Comment by canufeel** [comment]
My mistake. Should have included the
 inlineScripts: true,
 inlineCss: true

as my polymerVulcanize props.
However i still can't get it working. Both basic-carousel and basic-carousel-fit are styling my images incorrectly while displaying both images at the same time :(

**Comment by JanMiksovsky** [comment]
Can you provide more detail so I can investigate further?

* Is the `selected` CSS class applied to only one image at a time?
* basic-carousel and basic-carousel-fit don't hide the other images -- they just try to ensure that they're outside the visible bounds of the component. basic-carousel should set the width of the images such that they completely fill the component area. E.g., in the [basic-carousel demo](http://basic-web-components.github.io/basic-web-components/src/basic-carousel/?dom=shadow), there are 5 images, so they're each made to be 20% as wide as the horizontally scrolling surface, which is 500% the width of the component. Hence, each image should be 100% the width of the component. basic-carousel-fit does something similar, but calculates a different value for the `left` attribute of each image. Can you verify that the image `width`/`left` is being set as in the demos?
* If you're using basic-carousel, can you verify that the component has been styled to the height and width you want?
* If it's possible to run directly the original unvulcanized source, does the carousel work then? I normally develop without vulcanize (as above, vulcanize can introduce issues of its own), and then only add vulcanized when I've got things working as expected.
* Can you share any other details, or share code if that's possible?

Also: which browser are you using?

**Comment by JanMiksovsky** [comment]
@canufeel Just wondering if you were still interested in this issue.

**Comment by Jamtis** [comment]
I got this exact issue when I imported the HTMLs from raw.githubusercontent.com instead of rawgit.com and therefore with a "text/plain" MIME type.

**Comment by JanMiksovsky** [comment]
@Jamtis That particular case sounds like an issue using HTML Imports against a server that's not really set up for that. If so, this issue would lie far below the level at this code works. We're working on a solution for serving up these source files so that they can be properly imported from a server with, among other things, the correct MIME type. That's not ready for use yet, however.

Given the age of the original issue, and that we don't have more details to go on right now, I'm going to close this. If anyone hits this again and can provide a repro case, please reopen! Thanks.
